app <- ShinyDriver$new("../../", seed = 123)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(sidebarCollapsed = FALSE)
app$setInputs(tabs = "rates")
app$snapshot()
app$setInputs(tabs = "arrests")
app$snapshot()
app$setInputs(tabs = "crime")
app$snapshot()
